apiVersion: v1
kind: Pod
metadata: 
  labels:
    app: mypod
spec:
  containers:
    - image: nginx:latest
      name: hello-world
      ports:
      - containerPort: 80
        name: http
        protocol: TCP         