apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mytestpod
  name: mytestpod
spec:
  containers:
  - image: nginx
    name: mytestpod
    resources: 
      requests:
        memory: "100Mi"
        cpu: "0.5"
      limits:
        memory: "200Mi"
        cpu: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
