apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app
  labels:
    app: my-app
    type: front-end

spec:
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
      - name: my-app
        image: nginx:latest
  replicas: 3      