apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset2
  labels:
    app: my-app
    type: front-end

spec:
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        type: front-end
    spec:
      containers:
      - name: my-app-pod
        image: nginx:latest

  replicas: 2
  selector:
    matchLabels:
      type: front-end
      app: my-app
