apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-dev
  namespace: dev

spec:
  hard:
    pods: "5"
    requests.cpu: "2"
    requests.memory: "1Gi"
    limits.cpu: "3"
    limits.memory: "1.5Gi"     